version: "3"
services:
  # localhost:8123
  hass:
    image: homeassistant/home-assistant:2025.1.2
    restart: unless-stopped
    volumes:
      - ./hass:/config
      - ./custom_components:/config/custom_components:ro
    environment:
      TZ: Europe/Stockholm
    ports: [ "8123:8123" ]
  lint:
    image: cimg/python:3.13
    volumes: [ "./:/files:ro" ]
    working_dir: /files
    entrypoint: [ pylint ]
    command:
      - custom_components/purei9
      - tests
  test:
    image: cimg/python:3.13
    volumes: [ "./:/files:ro" ]
    working_dir: /files
    entrypoint: [ python3 ]
    command:
      - -m
      - unittest
      - discover
      - --start-directory
      - tests
      - --verbose
